// cardData.ts

import image1 from '../img/card1.png';
import image2 from '../img/card2.png';
import image3 from '../img/card3.png';
import image4 from '../img/card4.jpeg';

export const cardsData = [
  {
    id: 1,
    image: image1,
    title: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 'Rp 2.500.000',
    oldPrice: 'Rp 3.500.000',
    badge: '30%',
  },
  {
    id: 2,
    image: image2,
    title: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 'Rp 2.500.000',
  },
  {
    id: 3,
    image: image3,
    title: 'Lolito',
    description: 'Luxury big sofa',
    price: 'Rp 7.000.000',
    oldPrice: 'Rp 14.000.000',
    badge: '50%',
  },
  {
    id: 4,
    image: image4,
    title: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 'Rp 500.000',
    badge: 'New',
  },
  {
    id: 2,
    image: image2,
    title: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 'Rp 2.500.000',
  },
  {
    id: 1,
    image: image1,
    title: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 'Rp 2.500.000',
    oldPrice: 'Rp 3.500.000',
    badge: '30%',
  },
  {
    id: 4,
    image: image4,
    title: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 'Rp 500.000',
    badge: 'New',
  },
  {
    id: 3,
    image: image3,
    title: 'Lolito',
    description: 'Luxury big sofa',
    price: 'Rp 7.000.000',
    oldPrice: 'Rp 14.000.000',
    badge: '50%',
  },
  {
    id: 1,
    image: image1,
    title: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 'Rp 2.500.000',
    oldPrice: 'Rp 3.500.000',
    badge: '30%',
  },
  {
    id: 2,
    image: image2,
    title: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 'Rp 2.500.000',
  },
  {
    id: 3,
    image: image3,
    title: 'Lolito',
    description: 'Luxury big sofa',
    price: 'Rp 7.000.000',
    oldPrice: 'Rp 14.000.000',
    badge: '50%',
  },
  {
    id: 4,
    image: image4,
    title: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 'Rp 500.000',
    badge: 'New',
  },
  {
    id: 1,
    image: image1,
    title: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 'Rp 2.500.000',
    oldPrice: 'Rp 3.500.000',
    badge: '30%',
  },
  {
    id: 3,
    image: image3,
    title: 'Lolito',
    description: 'Luxury big sofa',
    price: 'Rp 7.000.000',
    oldPrice: 'Rp 14.000.000',
    badge: '50%',
  },
  {
    id: 2,
    image: image2,
    title: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 'Rp 2.500.000',
  },
  {
    id: 4,
    image: image4,
    title: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 'Rp 500.000',
    badge: 'New',
  },
  {
    id: 3,
    image: image3,
    title: 'Lolito',
    description: 'Luxury big sofa',
    price: 'Rp 7.000.000',
    oldPrice: 'Rp 14.000.000',
    badge: '50%',
  },
  {
    id: 4,
    image: image4,
    title: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 'Rp 500.000',
    badge: 'New',
  },
  {
    id: 2,
    image: image2,
    title: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 'Rp 2.500.000',
  },
  {
    id: 1,
    image: image1,
    title: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 'Rp 2.500.000',
    oldPrice: 'Rp 3.500.000',
    badge: '30%',
  },
  {
    id: 4,
    image: image4,
    title: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 'Rp 500.000',
    badge: 'New',
  },
  {
    id: 3,
    image: image3,
    title: 'Lolito',
    description: 'Luxury big sofa',
    price: 'Rp 7.000.000',
    oldPrice: 'Rp 14.000.000',
    badge: '50%',
  },
  {
    id: 1,
    image: image1,
    title: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 'Rp 2.500.000',
    oldPrice: 'Rp 3.500.000',
    badge: '30%',
  },
  {
    id: 2,
    image: image2,
    title: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 'Rp 2.500.000',
  },
];
